services:
  web:
    image: komqaq/arcp-paper-discussion:latest
    ports:
      - "5001:5001"

    volumes:
      - ./instance:/app/instance
    env_file:
      - .env
    restart: always
    container_name: arcp-paper-discussion
    environment:
      - TZ=Asia/Shanghai 
