version: '3'

services:
  web:
    image: komqaq/arcp-paper-discussion:latest
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    restart: always
    container_name: arcp-paper-discussion
    environment:
      - TZ=Asia/Shanghai 
